name: Fetch All Data
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess/*.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2

      - name: rude_golems - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://reqbin.com/echo/get/json
          downloaded_filename: rude_golems__magiceden.json
          postprocess: ./postprocess/magiceden.ts

      - name: rude_golems - Fetch Solanart data
        uses: githubocto/flat@v3
        with:
          http_url: https://qzlsklfacc.medianetwork.cloud/get_nft?collection=rudegolems&page=0&limit=100&order=price-ASC&fits=any&trait=&search=&min=0&max=0&listed=true&ownedby=&attrib_count=&bid=all
          downloaded_filename: rude_golems__solanart.json
          postprocess: ./postprocess/solanart.ts

      - name: sea_shanties - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://reqbin.com/echo/get/json
          downloaded_filename: sea_shanties__magiceden.json
          postprocess: ./postprocess/magiceden.ts

      - name: balloonsville - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://reqbin.com/echo/get/json
          downloaded_filename: balloonsville__magiceden.json
          postprocess: ./postprocess/magiceden.ts

      - name: balloonsville - Fetch Solanart data
        uses: githubocto/flat@v3
        with:
          http_url: https://qzlsklfacc.medianetwork.cloud/get_nft?collection=balloonsville&page=0&limit=100&order=price-ASC&fits=any&trait=&search=&min=0&max=0&listed=true&ownedby=&attrib_count=&bid=all
          downloaded_filename: balloonsville__solanart.json
          postprocess: ./postprocess/solanart.ts
